/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  CalendarOverview as CalendarOverview
} from './components/calendar-overview/calendar-overview';

declare global {
  interface HTMLCalendarOverviewElement extends CalendarOverview, HTMLElement {
  }
  var HTMLCalendarOverviewElement: {
    prototype: HTMLCalendarOverviewElement;
    new (): HTMLCalendarOverviewElement;
  };
  interface HTMLElementTagNameMap {
    "calendar-overview": HTMLCalendarOverviewElement;
  }
  interface ElementTagNameMap {
    "calendar-overview": HTMLCalendarOverviewElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "calendar-overview": JSXElements.CalendarOverviewAttributes;
    }
  }
  namespace JSXElements {
    export interface CalendarOverviewAttributes extends HTMLAttributes {
      
    }
  }
}

